move parameters to env.variables. update README. add tables for the given steps

diff --git a/executeTests b/executeTests
--- a/executeTests
+++ b/executeTests
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 #
-# ownCloud Android scenario tests
+# ownCloud iOS scenario tests
 #
 # @author Jesus Recio (@jesmrec)
-# Copyright (C) 2020 ownCloud GmbH.
+# Copyright (C) 2021 ownCloud GmbH.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License version 2,
@@ -22,29 +22,35 @@
 help()
 {
    echo ""
-   echo "Usage: $0 -s <ownCloud Server URL> -o <host> -t <filter> -a <Appium Server URL> -d <device UID> "
+   echo "Usage: $0 -t <filter>"
    echo ""
-   echo -e "\t-s (mandatory) URL of ownCloud server to test against"
-   echo -e "\t-a (optional) Appium server URL. if Appium Server is not specified, will be used \"localhost:4723/wd/hub\""
-   echo -e "\t-t (optional) Filter. F. ex: @createfolder will send only tests tagged with such label. Tags are allowed to concatenate, sepparated by \",\". It is also allowed to use a classpath to execute all the test in such class"
-   echo -e "\t-d (optional) In case of several devices attached, tests will be sent against the UID set in this option"
-   echo -e "\t-o (optional) Host name. If your server is stored in subfolders, this is pretty recommended"
-   echo -e "\t-h shows this help"
-   echo ""
-   exit 1 
+   echo -e "\t-t <filter> Used to execute tagged tests. F. ex: @createfolder will send only tests tagged with such label. OR/AND operations are allowed. It is also allowed to use a classpath to execute all the test in such class"
+   echo -e ""
+   echo -e "Examples:"
+   echo -e ""
+   echo -e "\t\t ./executeTests -t \"@createfolder\" -> This will execute only tests with the tag @createfolder"
+   echo -e ""
+   echo -e "\t\t ./executeTests -t \"'@createfolder and @copy'\" -> This will execute tests tagged with both @createfolder and @copy"
+   echo -e ""
+   echo -e "\t\t ./executeTests -t \"'@createfolder or @copy'\" -> This will execute tests tagged with @createfolder or @copy"
+   echo -e ""
+   echo -e "\t\t ./executeTests  -> This will execute all the tests"
+   echo -e ""
+   echo -e "Some environment variables are needed to work as well:"
+   echo -e ""
+   echo -e "\t\t\$OC_SERVER_URL (mandatory): URL of ownCloud server to test against"
+   echo -e ""
+   echo -e "\t\t\$APPIUM_URL (optional): Appium server URL. if Appium Server is not specified, will be used \"localhost:4723/wd/hub\""
+   echo -e ""
+   echo -e "The option -h: will show this help"
+   echo -e ""
+   echo -e ""
+   exit 1
 }
 
-while getopts ":t:a:s:d:h" opt; do
+while getopts "t::h" opt; do
   case $opt in
     t) tags="$OPTARG"
-    ;;
-    a) appium="$OPTARG"
-    ;;
-    s) oc="$OPTARG"
-    ;;
-    d) device="$OPTARG"
-    ;;
-    o) host="$OPTARG"
     ;;
     h) help
     ;;
@@ -53,35 +59,29 @@ while getopts ":t:a:s:d:h" opt; do
   esac
 done
 
-if [ $# -eq 0 ]
+export oc=$OC_SERVER_URL
+export appium=$APPIUM_URL
+
+if [ -z "$oc" ]
 then
-  help
-elif [ -z "$oc" ]
-then
-   echo "ownCloud Server URL is missing";
+   echo "ownCloud Server URL is missing. Please export the variable OC_SERVER_URL with the server URL to test against";
    help
 fi
 
 echo "Appium server: $appium"
 echo "oC server: $oc"
 echo "tags: $tags"
-echo "device: $device"
-echo "host: $host"
 
 if [ -z "$tags" ]
 then
  ./gradlew clean test aggregate \
   --info \
   -Dappium=$appium \
-  -Ddevice=$device \
   -Dserver=$oc
-  -Dhost=$host
 else
   ./gradlew clean test aggregate \
   --info \
   -Dcucumber.options="--tags $tags" \
   -Dappium=$appium \
-  -Ddevice=$device \
   -Dserver=$oc
-  -Dhost=$host
 fi
